// Deus ta vendo vc roubar em!!
const words = [
  { word: "abacaxi", clue: "Fruta tropical" },
  { word: "elefante", clue: "Animal de grande porte com tromba longa" },
  { word: "computador", clue: "Dispositivo eletronico" },
  { word: "girafa", clue: "Animal alto, com pescoço longo" },
  { word: "chocolate", clue: "Doce feito de cacau" },
  { word: "piano", clue: "Instrumento musical com teclas" },
  { word: "tigre", clue: "Felino selvagem" },
  { word: "esmeralda", clue: "Tipo de pedra preciosa" },
  { word: "navio", clue: "Embarcacao no mar" },
  { word: "telefone", clue: "Dispositivo de comunicacao" },
  { word: "floresta", clue: "Area com muitas arvores" },
  { word: "quadrado", clue: "Figura geometrica de quatro lados" },
  { word: "foguete", clue: "Veiculo espacial" },
  { word: "sorvete", clue: "Doce gelado" },
  { word: "bicicleta", clue: "Veiculo de duas rodas" },
  { word: "aviao", clue: "Meio de transporte aereo" },
  { word: "macaco", clue: "Primate arboreo" },
  { word: "raios", clue: "Descargas eletricas na atmosfera" },
  { word: "montanha", clue: "Elevacao natural da terra" },
  { word: "vela", clue: "Objeto para iluminacao" },
  { word: "camelo", clue: "Animal com corcova" },
  { word: "teatro", clue: "Lugar para assistir a pecas" },
  { word: "escola", clue: "Instituicao para aprendizado" },
  { word: "oculista", clue: "Especialista em visao" },
  { word: "refrigerante", clue: "Bebida gaseificada" },
  { word: "pinguim", clue: "Ave que vive no gelo" },
  { word: "lagarto", clue: "Reptil com cauda longa" },
  { word: "aviario", clue: "Local para aves" },
  { word: "cebola", clue: "Legume com camada externa" },
  { word: "cachoeira", clue: "Queda dagua natural" },
  { word: "biblioteca", clue: "Lugar para livros" },
  { word: "chaveiro", clue: "Pessoa que faz chaves" },
  { word: "futebol", clue: "Esporte com bola" },
  { word: "ponte", clue: "Estrutura para atravessar" },
  { word: "calendario", clue: "Sistema de datas" },
  { word: "brisa", clue: "Vento leve" },
  { word: "girassol", clue: "Flor que segue o sol" },
  { word: "relogio", clue: "Dispositivo para medir o tempo" },
  { word: "espanhol", clue: "Lingua falada na Espanha" },
  { word: "ferramenta", clue: "Objeto usado em trabalhos manuais" },
  { word: "estrela", clue: "Corpo celeste brilhante" },
  { word: "cachorro", clue: "Animal de estimacao popular" },
  { word: "jardim", clue: "Area de cultivo de plantas" },
  { word: "musica", clue: "Arte de combinar sons" },
  { word: "astronauta", clue: "Pessoa que viaja para o espaco" },
  { word: "cachimbo", clue: "Objeto para fumar" },
  { word: "televisao", clue: "Aparelho para assistir a programas" },
  { word: "camiseta", clue: "Roupagem casual" },
  { word: "solucao", clue: "Resposta para um problema" },
  { word: "sabo", clue: "Produto para lavar" },
  { word: "lago", clue: "Corpo de agua doce" },
  { word: "panela", clue: "Utensilio de cozinha" },
  { word: "trompete", clue: "Instrumento musical de metal" },
  { word: "marmelada", clue: "Doce feito de frutas" },
  { word: "rosas", clue: "Flores populares em jardins" },
  { word: "atleta", clue: "Pessoa que pratica esportes" },
  { word: "arcoiris", clue: "Fenomeno optico apos a chuva" },
  { word: "teclado", clue: "Dispositivo para digitacao" },
  { word: "coracao", clue: "Orgão vital do corpo" },
  { word: "eletricidade", clue: "Energia para funcionamento de aparelhos" }
];

export default function getWord() {
const index = Math.floor(Math.random() * words.length);
return words[index];
}
